In [333]:
def get_data(ticker):
    import requests
    import pandas as pd
    import io
    import numpy as np

    # parameters to modify in the query
    payload = {
    'output':'csv',
    'startdate':'2000-01-01',
    'enddate':'2014-01-01',
    'q':ticker
    }

    URL = 'http://www.google.com/finance/historical' # base URL

    r = requests.get(URL, params=payload).content # create the requests object
    df = pd.read_csv(io.StringIO(r.decode('utf-8')))
    
    # dropping unnecessary columns and setting the index as datetime
    df = df.drop(['Open', 'High', 'Low', 'Volume'], axis=1)
    df.set_index('Date', inplace=True)
    df.index = df.index.to_datetime()
    
    # DataFrame manipulation
    offset_1, offset_2, offset_3 = 252, (252*2), (252*3) # approximately one year, two years and three years
    df_length = len(df) - three_year_offset # determines the maximum length possible for our dataframe
    
    x_3 = df[:df_length] # target variable
    x_2 = df[offset_1:df_length + offset_1] # one year offset
    x_1 = df[offset_2:df_length + offset_2] # two year offset
    x_0 = df[offset_3: df_length + offset_3] # three year_offset
   
    # modify the indexes so we can concatenate the dataframes
    x_3 = x_3.reset_index().drop('index', axis=1)
    x_2 = x_2.reset_index().drop('index', axis=1)
    x_1 = x_1.reset_index().drop('index', axis=1)
    x_0 = x_0.reset_index().drop('index', axis=1)
    
    frames = [x_0, x_1, x_2, x_3] # list of dataframes to pass into pd.concat
    
    # concat the dataframes and rename the columns
    final_df = pd.concat(frames, axis=1)
    final_df.columns = ['x_0', 'x_1', 'x_2', 'y']
    
    return final_df

In [ ]:
train_list = ["TMO", "FOXL","AMZN","APPL","GM","IBM","TWTR","CBS","TM","BIO"]

In [337]:
get_data('AAPL')

/Users/gmaclenn/anaconda2/lib/python2.7/site-packages/ipykernel/__main__.py:23: FutureWarning: to_datetime is deprecated. Use pd.to_datetime(...)

        x_0    x_1    x_2      y
0     46.47  57.52  76.02  80.15
1     46.50  58.08  72.80  79.22
2     46.38  57.62  73.58  80.01
3     46.23  56.94  73.29  80.56
4     46.45  56.64  74.31  81.10
5     46.32  56.56  74.19  81.44
6     46.03  54.60  74.53  78.43
7     45.80  54.43  75.19  77.78
8     45.89  54.13  76.27  78.68
9     45.77  54.31  74.12  79.28
10    45.76  55.54  72.83  79.64
11    45.95  55.98  75.67  79.20
12    45.79  56.23  77.00  80.08
13    45.68  55.81  77.34  80.19
14    45.86  55.58  75.69  80.79
15    45.46  55.85  76.18  80.92
16    45.74  56.14  78.18  80.00
17    45.35  55.67  76.97  81.13
18    45.45  55.42  82.26  80.71
19    45.20  54.60  83.74  80.90
20    44.45  53.31  83.61  78.75
21    45.27  53.73  84.19  79.44
22    45.00  51.94  83.28  77.99
23    44.97  52.43  83.54  76.20
24    44.10  53.79  84.22  74.82
25    44.77  52.72  81.64  74.26
26    43.82  53.56  80.24  74.45
27    44.06  53.92  80.13  73.57
28    42.93  54.97  80.82  74.22
29    43.08  55.55  75.38  74.09
...     ...    ...    ...    ...
2734   4.14   1.37   1.65   1.06
2735   3.88   1.41   1.62   1.06
2736   4.05   1.37   1.71   1.09
2737   4.02   1.48   1.76   1.05
2738   4.10   1.48   1.79   1.04
2739   4.07   1.51   1.76   1.03
2740   3.86   1.44   1.78   1.02
2741   3.69   1.47   1.72   1.02
2742   3.53   1.51   1.74   1.01
2743   3.58   1.54   1.76   1.03
2744   3.71   1.55   1.82   1.03
2745   3.63   1.55   1.81   1.04
2746   3.93   1.40   1.74   1.05
2747   3.94   1.42   1.77   1.03
2748   4.01   1.46   1.72   1.02
2749   3.79   1.46   1.65   1.07
2750   3.98   1.38   1.66   1.04
2751   4.05   1.39   1.66   1.01
2752   3.81   1.33   1.66   0.99
2753   3.71   1.20   1.64   1.01
2754   3.59   1.22   1.56   0.99
2755   3.46   1.23   1.58   1.00
2756   3.11   1.29   1.61   1.01
2757   3.31   1.18   1.48   1.04
2758   3.49   1.23   1.55   1.03
2759   3.54   1.18   1.51   1.04
2760   3.39   1.17   1.50   1.04
2761   3.71   1.22   1.52   1.05
2762   3.66   1.17   1.55   1.05
2763   4.00   1.06   1.62   1.04

[2764 rows x 4 columns]

In [317]:
def create_target():
    test

In [282]:
test

         x_0     x_1     x_2       y
0     300.20  319.53  353.34  559.79
1     299.16  319.80  349.65  554.18
2     300.89  316.25  352.79  558.64
3     301.81  314.54  354.08  558.17
4     302.44  312.60  354.40  555.36
5     301.23  314.87  357.46  556.99
6     297.23  310.60  360.82  549.76
7     295.10  312.67  359.69  542.57
8     295.56  309.46  360.17  541.83
9     294.85  308.73  360.03  534.40
10    297.16  312.50  350.63  535.95
11    297.01  312.38  351.00  529.86
12    295.81  313.40  348.43  534.45
13    295.45  307.72  348.09  538.11
14    294.97  311.38  342.37  541.79
15    293.28  311.57  341.76  538.53
16    288.89  312.51  345.22  534.40
17    286.21  309.87  343.57  528.14
18    285.62  306.58  345.17  528.56
19    281.89  299.40  347.28  526.10
20    277.58  291.17  348.84  526.71
21    290.76  293.80  345.60  529.27
22    294.70  281.22  341.49  531.02
23    297.19  284.77  335.02  528.68
24    291.21  289.71  330.24  522.44
25    295.31  290.18  333.65  515.43
26    295.12  297.14  332.60  516.52
27    297.98  300.13  334.65  510.64
28    291.48  305.43  333.77  512.09
29    291.57  307.97  323.27  515.26
...      ...     ...     ...     ...
1478   96.40  171.49  230.50  264.56
1479   93.61  172.68  232.73  265.86
1480   93.90  181.12  229.32  267.04
1481   95.69  179.21  228.92  258.79
1482   99.22  184.36  230.71  260.32
1483   97.92  183.78  235.28  258.09
1484  102.08  192.36  234.77  252.22
1485  105.32  190.59  235.50  250.60
1486  102.88  197.82  233.35  253.15
1487   95.85  200.69  240.51  247.47
1488   97.71  216.11  240.63  257.69
1489   95.07  213.20  250.50  281.87
1490   93.95  216.53  246.91  273.86
1491   94.53  216.92  245.99  274.98
1492   88.47  216.28  247.67  277.71
1493   90.27  221.29  243.80  282.92
1494   94.05  213.54  249.28  286.96
1495   96.86  199.53  239.29  274.04
1496   98.55  218.00  240.18  291.88
1497  101.85  222.23  244.63  299.82
1498   99.89  233.32  243.67  300.09
1499   97.57  232.89  248.39  307.67
1500   97.59  231.58  251.89  318.51
1501   96.67  235.58  252.25  326.58
1502   97.43  234.65  249.61  318.81
1503   96.83  233.22  244.49  323.04
1504   94.18  232.60  242.51  326.27
1505   96.66  225.39  241.55  315.52
1506   97.15  222.40  243.35  324.30
1507  101.25  217.40  241.39  328.17

[1508 rows x 4 columns]

In [264]:
df_length = len(test) - three_year_offset # determines the maximum length possible for our dataframe
x_3 = test[:df_length]
x_2 = test[one_yr_offset:df_length+one_yr_offset]
x_1 = test[two_year_offset:df_length+two_year_offset]
x_0 = test[three_year_offset: df_length + three_year_offset]

one_yr_offset = 252 # approximately one year
two_year_offset = (252*2)
three_year_offset = (252*3)
# print type(x_3), x_2, x_1, x_0

# frames = [x_3, x_2, x_1,]

# pd.concat(x_0, axis=1, join='outer', ignore_index=True)

In [272]:
x_3 = x_3.reset_index().drop('index', axis=1)
x_2 = x_2.reset_index().drop('index', axis=1)
x_1 = x_1.reset_index().drop('index', axis=1)
x_0 = x_0.reset_index().drop('index', axis=1)

In [274]:
frames = [x_0, x_1, x_2, x_3]

In [278]:
final_df = pd.concat(frames, axis=1)
final_df.columns = ['x_0', 'x_1', 'x_2', 'y']

(1508, 4)

In [330]:
def basic_get_data(ticker):
    import requests
    import pandas as pd
    import io
    import numpy as np
    date_list = []
    close_list = []
    # parameters to modify in the query
    payload = {
    'output':'csv',
    'startdate':'2000-01-01',
    'enddate':'2014-01-01',
    'q':ticker
    }

    URL = 'http://www.google.com/finance/historical' # base URL

    r = requests.get(URL, params=payload).content # create the requests object
    df = pd.read_csv(io.StringIO(r.decode('utf-8')))
    
    # dropping unnecessary columns and setting the index as datetime
# #     df = df.drop(['Open', 'High', 'Low', 'Volume'], axis=1)
#     df.set_index('Date', inplace=True)
#     df.index = df.index.to_datetime()
    
    return df

In [331]:
basic_get_data('FOXL')

Empty DataFrame
Columns: [<!DOCTYPE html><html lang=en><meta charset=utf-8><meta name=viewport content="initial-scale=1,  minimum-scale=1,  width=device-width"><title>Error 400 (Not Found)!!1</title><style>*{margin:0;padding:0}html, code{font:15px/22px arial, sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px;}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}pre{white-space:pre-wrap;}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}</style><div id="af-error-container"><a href=//www.google.com/><span id=logo aria-label=Google></span></a><p><b>400.</b> <ins>That’s an error.</ins><p>The requested URL was not found on this server. <ins>That’s all we know.</ins></div>]
Index: []

In [175]:
print test.idxmax()
print test.idxmin()

Close   2013-12-31
dtype: datetime64[ns]
Close   2008-11-24
dtype: datetime64[ns]