### Intro: find missing data

In [12]:
import pandas as pd
import numpy as np
import math

In [13]:
# Here's building a function using def: 

def square_root(x): return math.sqrt(x)

In [14]:
# Here's building the same function using lambda
x = lambda x: math.sqrt(x)

In [15]:
# Use the isnull() method to detect the missing values. The output
# shows True when the value is missing. By adding an index into 
# the dataset, you obtain just the entries that are missing.
# A dataset could represent missing data in several ways. In this 
# example, you see missing data represented as np.NaN (NumPy Not 
# a Number) and the Python None value.

### Intro: fill in missing data

In [16]:
# To fill in missing data use fillna(). For fillna() you need to 
# provide a number. Usually, the mean, median, or mode is used. 
# Let's use the same data set and this time let's fill in missing 
# values with the mean.

In [17]:
# We could also just drop all the NAs, by using dropna()

### Write the equivalent lambda function

In [18]:
# Write the equivalent lambda function for the following def 
# function: 

def f (x): return(x**2)
print(f(8))

64

In [19]:
# equivalent lambda function

g = lambda x = 8: x ** 2
g(8)

64

### Lab 3.4

In [20]:
# read in the raw data from the github url

data = pd.read_csv("https://raw.githubusercontent.com/suneel0101/lesson-plan/master/crunchbase_monthly_export.csv")

In [21]:
# find missing values
missing_data = data[data.isnull()]
missing_data

,permalink,name,homepage_url,category_list,market,funding_total_usd,status,country_code,state_code,region,city,funding_rounds,founded_at,founded_month,founded_quarter,founded_year,first_funding_at,last_funding_at,Unnamed: 18
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44920,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44921,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44922,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44923,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44924,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44925,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44926,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44927,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44928,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44929,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44930,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44931,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44932,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44933,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44934,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44935,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44936,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44937,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44938,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44939,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44940,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44941,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44942,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44943,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44944,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44945,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44946,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44947,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44948,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44949,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [22]:
# fill in missing data with the mean
filled_data = data[data.notnull()]

In [23]:
filled_data.head()

,permalink,name,homepage_url,category_list,market,funding_total_usd,status,country_code,state_code,region,city,funding_rounds,founded_at,founded_month,founded_quarter,founded_year,first_funding_at,last_funding_at,Unnamed: 18
0,/organization/canal-do-credito,Canal do Credito,http://www.canaldocredito.com.br,|Credit|Technology|Services|Finance|,Credit,"750,000",NaN,BRA,NaN,Rio de Janeiro,Belo Horizonte,1,NaN,NaN,NaN,NaN,1/1/10,1/1/10,NaN
1,/organization/waywire,#waywire,http://www.waywire.com,|Entertainment|Politics|Social Media|News|,Entertainment,"1,750,000",acquired,USA,NY,New York City,New York,1,6/1/12,2012-06,2012-Q2,2012.0,6/30/12,6/30/12,NaN
2,/organization/tv-communications,&TV Communications,http://enjoyandtv.com,|Games|,Games,"4,000,000",operating,USA,CA,Los Angeles,Los Angeles,2,NaN,NaN,NaN,NaN,6/4/10,9/23/10,NaN
3,/organization/rock-your-paper,'Rock' Your Paper,http://www.rockyourpaper.org,|Publishing|Education|,Education,"40,000",operating,EST,NaN,Tallinn,Tallinn,1,10/26/12,2012-10,2012-Q4,2012.0,8/9/12,8/9/12,NaN
4,/organization/in-touch-network,(In)Touch Network,http://www.InTouchNetwork.com,|Electronics|Guides|Coffee|Restaurants|Music|i...,Apps,"1,500,000",operating,GBR,NaN,London,London,1,4/1/11,2011-04,2011-Q2,2011.0,4/1/11,4/1/11,NaN

In [24]:
# Set status to categorical
statuses = pd.DataFrame(data[data['status'].notnull()]['status'], dtype = 'category')

# Find mode status
print(pd.get_dummies(statuses, prefix = "", prefix_sep = "").mode())
statuses['status'].value_counts()

   acquired  closed  operating
0       0.0     0.0        1.0

operating    36135
acquired      3194
closed        2879
Name: status, dtype: int64

In [25]:
# Therefore we can set any empty statuses to 'operating' without losing much accuracy
data['status'] = data['status'].fillna('operating')

print(data['status'].head())

0    operating
1     acquired
2    operating
3    operating
4    operating
Name: status, dtype: object

In [26]:
#find matching regions to fill in state
regions_dataframe = data[['region','state_code']].dropna(axis = 0)#.drop_duplicates()
regions_dataframe.head()

                   region state_code
1           New York City         NY
2             Los Angeles         CA
6          Ft. Lauderdale         FL
9   Springfield, Illinois         IL
10            SF Bay Area         CA

In [27]:
empty_states = data[data['state_code'].isnull()]

,region,state_code_x,permalink,name,homepage_url,category_list,market,funding_total_usd,status,country_code,state_code_y,city,funding_rounds,founded_at,founded_month,founded_quarter,founded_year,first_funding_at,last_funding_at,Unnamed: 18
0,New York City,NY,/organization/black-rhino-group,Black Rhino Group,http://www.blackrhinogroup.com/,NaN,NaN,-,operating,NaN,NaN,New York,1.0,NaN,NaN,NaN,NaN,7/30/14,7/30/14,NaN
1,New York City,NY,/organization/commonbond,CommonBond,http://commonbond.co,|Finance|,Finance,"103,500,000",operating,NaN,NaN,New York,2.0,11/1/11,2011-11,2011-Q4,2011.0,11/29/12,9/4/13,NaN
2,New York City,NY,/organization/prospect-accelerator,Prospect Accelerator,http://www.prospectaccelerator.com,|Advertising|,Advertising,-,operating,NaN,NaN,Manhattan,1.0,10/1/12,2012-10,2012-Q4,2012.0,10/1/12,10/1/12,NaN
3,Los Angeles,CA,/organization/geocities,GeoCities,NaN,|Web Hosting|,Web Hosting,"40,000,000",closed,NaN,NaN,Marina Del Rey,4.0,1/1/96,1996-01,1996-Q1,1996.0,1/1/95,1/1/98,NaN
4,Los Angeles,CA,/organization/orbitera-inc,"Orbitera, Inc.",http://www.orbitera.com,|Cloud Computing|Marketing Automation|SaaS|,Cloud Computing,-,operating,NaN,NaN,West Hollywood,1.0,5/7/11,2011-05,2011-Q2,2011.0,5/7/11,5/7/11,NaN
5,Los Angeles,CA,/organization/peggd,Pegg'd,http://peggd.com/,|Events|Apps|,Apps,"65,000",operating,NaN,NaN,Los Angeles,1.0,11/27/12,2012-11,2012-Q4,2012.0,5/15/14,5/15/14,NaN
6,Ft. Lauderdale,FL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,"Springfield, Illinois",IL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,SF Bay Area,CA,/organization/kloudless,Kloudless,https://kloudless.com,|Developer APIs|Cloud Data Services|Software|,Cloud Data Services,"1,300,000",operating,NaN,NaN,Berkeley,1.0,12/1/11,2011-12,2011-Q4,2011.0,1/1/13,1/1/13,NaN
9,SF Bay Area,CA,/organization/krowdpad,KrowdPad,http://www.krowdpad.com,NaN,NaN,-,operating,NaN,NaN,Redwood City,1.0,2/1/13,2013-02,2013-Q1,2013.0,8/1/14,8/1/14,NaN
10,SF Bay Area,CA,/organization/lazarus-effect,Lazarus Effect,http://www.lazarus-effect.com/,NaN,NaN,"5,000,000",operating,NaN,NaN,Campbell,1.0,NaN,NaN,NaN,NaN,7/31/14,7/31/14,NaN
11,SF Bay Area,CA,/organization/metanautix,Metanautix,http://metanautix.com,|Analytics|,Analytics,"7,000,000",operating,NaN,NaN,Palo Alto,1.0,NaN,NaN,NaN,NaN,8/5/14,8/5/14,NaN
12,SF Bay Area,CA,/organization/shine-security,Shine Technologies Corp,http://getshine.com,|Cyber|Advertising|Security|,Advertising,"3,300,000",operating,NaN,NaN,Sunnyvale,2.0,1/1/11,2011-01,2011-Q1,2011.0,12/1/11,10/1/12,NaN
13,SF Bay Area,CA,/organization/sitejabber,SiteJabber,http://SiteJabber.com,|Reputation|Reviews and Recommendations|Curate...,Curated Web,-,operating,NaN,NaN,San Francisco,1.0,1/1/08,2008-01,2008-Q1,2008.0,3/1/10,3/1/10,NaN
14,SF Bay Area,CA,/organization/vufind,vufind,http://developers.vufind.com,|E-Commerce Platforms|Mobile Commerce|E-Commer...,Analytics,"930,000",operating,NaN,NaN,Walnut Creek,3.0,1/1/10,2010-01,2010-Q1,2010.0,9/1/10,7/1/12,NaN
15,North Carolina,NC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,Newark,NJ,/organization/flexwage-solutions,FlexWage Solutions,http://flexwage.com,NaN,NaN,"3,500,000",operating,NaN,NaN,Mountainside,1.0,NaN,NaN,NaN,NaN,8/4/14,8/4/14,NaN
17,Orlando,FL,/organization/florida-hospital,Florida Hospital,https://www.floridahospital.com/tampa,|Hospitality|,Hospitality,"2,000,000",operating,NaN,NaN,Orlando,1.0,NaN,NaN,NaN,NaN,7/30/14,7/30/14,NaN
18,Baltimore,MD,/organization/zero-chroma-llc,Zero Chroma LLC,http://www.zerochroma.com,|Fitness|Startups|iPad|iPhone|Tablets|Consumer...,Consumer Electronics,"1,000,000",operating,NaN,NaN,Baltimore,1.0,9/1/09,2009-09,2009-Q3,2009.0,11/9/12,11/9/12,NaN
19,"Portland, Oregon",OR,/organization/hallspot,Hallspot,http://hallspot.com,|Mobile|Colleges|Software|Curated Web|,Colleges,"1,000,000",operating,NaN,NaN,Portland,3.0,3/1/13,2013-03,2013-Q1,2013.0,5/17/13,8/4/14,NaN
20,Seattle,WA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,Cleveland,OH,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,Boston,MA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,Huntsville,AL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,Providence,RI,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,Chicago,IL,/organization/assignment-editor,Assignment Editor,http://assignmenteditor.com/,|News|,News,"1,000,000",operating,NaN,NaN,Chicago,2.0,7/1/99,1999-07,1999-Q3,1999.0,3/31/01,11/30/02,NaN
26,Chicago,IL,/organization/band-digital,Band Digital,NaN,|Internet Marketing|,Internet Marketing,"7,294,000",operating,NaN,NaN,Chicago,4.0,1/1/84,1984-01,1984-Q1,1984.0,7/15/09,2/9/12,NaN
27,Chicago,IL,/organization/beyond-credentials,Beyond Credentials,NaN,|Marketplaces|,Marketplaces,"75,000",operating,NaN,NaN,Chicago,2.0,1/1/98,1998-01,1998-Q1,1998.0,3/31/11,4/30/11,NaN
28,Chicago,IL,/organization/classbug,ClassBug,https://classbug.com/,|Payments|,Payments,"12,000",operating,NaN,NaN,Chicago,1.0,3/1/13,2013-03,2013-Q1,2013.0,3/15/12,3/15/12,NaN
29,Chicago,IL,/organization/extended-care-information-network,Extended Care Information Network,http://www.extendedcare.com/,|Enterprises|Health Care|,Enterprises,"16,000,000",acquired,NaN,NaN,Chicago,3.0,1/1/95,1995-01,1995-Q1,1995.0,1/31/00,3/31/01,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8452,United Kingdom,Wirral,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8453,United Kingdom,Cheshire East,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8454,United Kingdom,Sutton,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8455,Newfoundland,NL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8456,Dorset,Dorset,/organization/new-earth-solutions,New Earth Solutions,http://www.newearthsolutions.co.uk,|Clean Technology|,Clean Technology,"12,365,936",operating,GBR,NaN,Verwood,2.0,1/1/02,2002-01,2002-Q1,2002.0,2/14/08,12/10/09,NaN
8457,Dorset,Dorset,/organization/sugar-free-media,Sugar Free Media,http://www.sugarfreemedia.co.uk,|SEO|Advertising|,Advertising,"74,583",operating,GBR,NaN,Swanage,1.0,NaN,NaN,NaN,NaN,3/1/10,3/1/10,NaN
8458,Nottinghamshire,Nottinghamshire,/organization/activ8-intelligence,activ8 Intelligence,http://www.a8i.co.uk,|Software|,Software,"2,310,008",operating,GBR,NaN,Farnsfield,2.0,1/1/05,2005-01,2005-Q1,2005.0,3/6/07,3/29/13,NaN
8459,Nottinghamshire,Nottinghamshire,/organization/solar-capture-technologies,Solar Capture Technologies,http://solarcapturetechnologies.com/about,|Renewable Energies|,Renewable Energies,"339,987",operating,GBR,NaN,Blyth,1.0,1/1/12,2012-01,2012-Q1,2012.0,6/25/14,6/25/14,NaN
8460,United Kingdom,Gwynedd,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8461,Italy,Veneto,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8462,Lake Tahoe,CA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8463,Windsor,NL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8464,India,Punjab,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8465,Sherwood Park,ON,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8466,Mexico - Other,Mexico,/organization/agavideo,Agavideo,http://agavideo.com,NaN,NaN,"30,000",operating,MEX,NaN,mexico,1.0,NaN,NaN,NaN,NaN,10/15/11,10/15/11,NaN
8467,Mexico - Other,Mexico,/organization/atlantia-search,Atlantia Search,http://www.atlantiasearch.com/,NaN,NaN,"24,897",operating,MEX,NaN,NaN,1.0,1/1/12,2012-01,2012-Q1,2012.0,1/1/14,1/1/14,NaN
8468,Mexico - Other,Mexico,/organization/bandtastic,Bandtastic,http://bandtastic.me,|Crowdfunding|Startups|Music|,Crowdfunding,"70,202",operating,MEX,NaN,NaN,2.0,10/19/11,2011-10,2011-Q4,2011.0,11/1/11,3/1/13,NaN
8469,Mexico - Other,Mexico,/organization/cono-c,Cono-C,http://www.cono-c.com/,NaN,NaN,"24,509",operating,MEX,NaN,NaN,1.0,NaN,NaN,NaN,NaN,3/1/14,3/1/14,NaN
8470,Mexico - Other,Mexico,/organization/cursa-me,Cursa.me,https://www.cursa.me/,NaN,NaN,"49,197",operating,MEX,NaN,NaN,1.0,NaN,NaN,NaN,NaN,12/1/11,12/1/11,NaN
8471,Mexico - Other,Mexico,/organization/firstjob-2,FirstJob,http://www.firstjob.me/,NaN,NaN,"40,000",operating,MEX,NaN,NaN,1.0,1/1/12,2012-01,2012-Q1,2012.0,6/1/14,6/1/14,NaN
8472,Mexico - Other,Mexico,/organization/kubo-financiero,kubo financiero,http://www.kubofinanciero.com,|Finance Technology|Personal Finance|Finance|,Finance,"133,790",operating,MEX,NaN,M̩xico,1.0,7/25/12,2012-07,2012-Q3,2012.0,9/1/13,9/1/13,NaN
8473,Mexico - Other,Mexico,/organization/modebo,Modebo,http://www.modebo.com.mx,|Architecture|Clean Energy|Energy Efficiency|C...,Architecture,"49,477",operating,MEX,NaN,Mexico,1.0,9/28/10,2010-09,2010-Q3,2010.0,10/1/12,10/1/12,NaN
8474,Mexico - Other,Mexico,/organization/rubberit,rubberit,http://rubberit.co,|Education|Humanitarian|Sex|Health and Wellnes...,E-Commerce,"25,000",operating,MEX,NaN,Mexico,1.0,10/10/12,2012-10,2012-Q4,2012.0,10/10/12,10/10/12,NaN
8475,Mexico - Other,Mexico,/organization/schoolcontrol,SchoolControl,http://www.schoolcontrol.com,|All Students|Gamification|Big Data Analytics|...,All Students,"49,682",operating,MEX,NaN,Mexico,1.0,9/18/11,2011-09,2011-Q3,2011.0,10/1/12,10/1/12,NaN
8476,Mexico - Other,Mexico,/organization/tok3n,Tok3n,http://www.tok3n.com/,NaN,NaN,"25,025",operating,MEX,NaN,NaN,1.0,NaN,NaN,NaN,NaN,11/1/13,11/1/13,NaN
8477,Hawaii - Big Island,HI,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8478,Red Deer,AB,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8479,Manitoba,MB,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8480,New Brunswick,NB,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8481,"Columbus, Georgia",GA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN