## Clean data

In [276]:
import pandas as pd

In [277]:
python = pd.read_csv("./id_and_Python.csv",index_col='id')
del python['Unnamed: 0']
python = python.dropna()
python = python.reset_index().drop_duplicates(subset='id', keep='last').set_index('id')
python.head()
#python.index.value_counts()

                     Python
id
jl_f43cd8061406b3d7       1
jl_b59a64d3298e7fe8       1
jl_fbadb59b5f73dc18       1
jl_90603c7f1f0af480       1
jl_70351b5092814475       1

In [278]:
years = pd.read_csv("./id_years - removed_dupes.csv", index_col='id')
del years['Unnamed: 0']
#Using keep='last' here means we take the MOST years exp. necessary for each job
years = years.reset_index().drop_duplicates(subset='id', keep='last').set_index('id')
#years.index.value_counts()
years.head()

                     years
id
jl_61956da39b445a3c    0.0
jl_fbadb59b5f73dc18    0.0
jl_f5945f64ec7013e3    0.0
jl_50022587c7a4a8d9    0.0
jl_44da2bd2b0b7e145    0.0

In [279]:
scientist = pd.read_csv("./Scientist Classifier.csv", index_col='ID')
del scientist['Unnamed: 0']
scientist = scientist.dropna()
scientist = scientist.drop_duplicates()
scientist.head()
#scientist.index.value_counts()

                                                          Title  Classifier
ID
jl_70351b5092814475                   biomedical data scientist         1.0
jl_04a882314da504d4  mass spectrometry data analyst, usa-boston         0.0
jl_6c9d0349b46d0aae                       data insights analyst         0.0
jl_1b5a168dfc7b2712                              data scientist         1.0
jl_ada8a7b4477d3923              senior computer/data scientist         1.0

In [280]:
salary = pd.read_csv("./id_salary.csv", index_col='id')
del salary['Unnamed: 0']
salary.head()

                     over_90k
id
jl_85c4e91c561780aa         0
jl_e632343c455d80f9         0
jl_1b5a168dfc7b2712         0
jl_05654b2739edb3dc         0
jl_1a7766c45b1abbeb         0

In [281]:
phd = pd.read_csv("./phd_df.csv",index_col='job_id')
del phd['Unnamed: 0']
phd = phd.reset_index().drop_duplicates(subset='job_id', keep='last').set_index('job_id')
phd.head()
#phd.index.value_counts()

                     has_phd                             title
job_id
jl_9587aad4baab10f1        1             Data Science Engineer
jl_8cce239a68b06ecc        1         Bioinformatics Engineer I
jl_d5e17d142783f070        1                Research Scientist
jl_fa8592452682f9a1        1  Senior Machine Learning Engineer
jl_c110f141fea2888f        1         Senior Clinical Scientist

In [282]:
startup = pd.read_csv("./startup_df.csv",index_col='id')
del startup['Unnamed: 0']
startup = startup.reset_index().drop_duplicates(subset='id', keep='last').set_index('id')
startup.head()
#startup.index.value_counts()

                     has_startup
id
jl_b856f9a5bc9b6cef            1
jl_16adc2284667102e            1
jl_788467cccf1800c4            1
jl_28643ddfd474331d            1
jl_ec0c0eb870136905            1

## Merge Dataframes

In [283]:
df = pd.merge(python,years,how='outer', left_index=True, right_index=True, indicator='py_year')
#print(df.head())
#print(df.shape)

In [284]:
df = pd.merge(df,scientist,how='outer', left_index=True, right_index=True, indicator='scientist_merge')
#df = df.dropna()
df.rename(columns={'Classifier':'scientist_in_title'},inplace=True)
#df['scientist_in_title'] = df['scientist_in_title'].fillna(0)

In [285]:
df = pd.merge(df,salary,how='left',left_index=True,right_index=True,indicator='salary_merge')

In [286]:
df = pd.merge(df,startup,how='left',left_index=True,right_index=True,indicator='startup_merge')

In [287]:
df = pd.merge(df,phd,how='left',left_index=True,right_index=True,indicator='phd_merge')
df['Python'] = df['Python'].fillna(0)
df['years'] = df['years'].fillna(0)
df['has_phd'] = df['has_phd'].fillna(0)
df['has_startup'] = df['has_startup'].fillna(0)
df['scientist_in_title'] = df['scientist_in_title'].fillna(0)

In [288]:
df.shape

(920, 13)

In [289]:
df.head()

,Python,years,py_year,Title,scientist_in_title,scientist_merge,over_90k,salary_merge,has_startup,startup_merge,has_phd,title,phd_merge
jl_f43cd8061406b3d7,1.0,0.0,left_only,NaN,0.0,left_only,1.0,both,0.0,left_only,0.0,NaN,left_only
jl_b59a64d3298e7fe8,1.0,0.0,left_only,NaN,0.0,left_only,1.0,both,0.0,left_only,0.0,NaN,left_only
jl_fbadb59b5f73dc18,1.0,0.0,both,NaN,0.0,left_only,1.0,both,0.0,left_only,0.0,NaN,left_only
jl_90603c7f1f0af480,1.0,0.0,both,NaN,0.0,left_only,1.0,both,0.0,left_only,0.0,NaN,left_only
jl_70351b5092814475,1.0,0.0,left_only,biomedical data scientist,1.0,both,1.0,both,0.0,left_only,1.0,Biomedical Data Scientist,both

In [290]:
df.head(100)

,Python,years,py_year,Title,scientist_in_title,scientist_merge,over_90k,salary_merge,has_startup,startup_merge,has_phd,title,phd_merge
jl_f43cd8061406b3d7,1.0,0.0,left_only,NaN,0.0,left_only,1.0,both,0.0,left_only,0.0,NaN,left_only
jl_b59a64d3298e7fe8,1.0,0.0,left_only,NaN,0.0,left_only,1.0,both,0.0,left_only,0.0,NaN,left_only
jl_fbadb59b5f73dc18,1.0,0.0,both,NaN,0.0,left_only,1.0,both,0.0,left_only,0.0,NaN,left_only
jl_90603c7f1f0af480,1.0,0.0,both,NaN,0.0,left_only,1.0,both,0.0,left_only,0.0,NaN,left_only
jl_70351b5092814475,1.0,0.0,left_only,biomedical data scientist,1.0,both,1.0,both,0.0,left_only,1.0,Biomedical Data Scientist,both
jl_05de118416baeef8,1.0,0.0,left_only,NaN,0.0,left_only,NaN,left_only,0.0,left_only,0.0,NaN,left_only
jl_50022587c7a4a8d9,1.0,0.0,both,NaN,0.0,left_only,1.0,both,0.0,left_only,0.0,NaN,left_only
jl_44da2bd2b0b7e145,1.0,0.0,both,NaN,0.0,left_only,1.0,both,0.0,left_only,1.0,Machine Learning Scientist,both
jl_f5945f64ec7013e3,1.0,0.0,both,NaN,0.0,left_only,1.0,both,0.0,left_only,0.0,NaN,left_only
jl_6c9d0349b46d0aae,1.0,4.0,both,data insights analyst,0.0,both,1.0,both,0.0,left_only,1.0,Data Insights Analyst,both
jl_32062be6a68c7531,1.0,4.0,both,NaN,0.0,left_only,1.0,both,0.0,left_only,1.0,Clinical Data Scientist (8570),both
jl_e632343c455d80f9,1.0,0.0,both,NaN,0.0,left_only,0.0,both,0.0,left_only,0.0,NaN,left_only
jl_4fbc1d778df8203e,1.0,3.0,both,NaN,0.0,left_only,1.0,both,0.0,left_only,0.0,NaN,left_only
jl_2370348e80d8c420,1.0,3.0,both,NaN,0.0,left_only,1.0,both,0.0,left_only,0.0,NaN,left_only
jl_85c4e91c561780aa,1.0,3.0,both,NaN,0.0,left_only,0.0,both,0.0,left_only,0.0,NaN,left_only
jl_ada8a7b4477d3923,1.0,3.0,both,senior computer/data scientist,1.0,both,1.0,both,0.0,left_only,1.0,Senior Computer/Data Scientist,both
jl_25732595a7113f45,1.0,2.0,both,NaN,0.0,left_only,1.0,both,0.0,left_only,0.0,NaN,left_only
jl_b3462acabd0f43c3,1.0,0.0,left_only,NaN,0.0,left_only,0.0,both,0.0,left_only,1.0,Bioinformatics Scientist,both
jl_45aa9a89795b5d2b,1.0,0.0,both,NaN,0.0,left_only,1.0,both,0.0,left_only,1.0,Senior Data Scientist,both
jl_2d63f589c7b4584b,1.0,2.0,both,NaN,0.0,left_only,1.0,both,0.0,left_only,1.0,Data Scientist,both
jl_b8658ac1d1483ab5,1.0,0.0,both,NaN,0.0,left_only,1.0,both,0.0,left_only,0.0,NaN,left_only
jl_40aa8253449c2054,1.0,2.0,both,NaN,0.0,left_only,0.0,both,1.0,both,0.0,NaN,left_only
jl_9d3c55e683467e2c,1.0,0.0,left_only,NaN,0.0,left_only,0.0,both,0.0,left_only,0.0,NaN,left_only
jl_b5b7c26924376b59,1.0,0.0,both,NaN,0.0,left_only,1.0,both,0.0,left_only,0.0,NaN,left_only
jl_69101ac67eec9ea2,1.0,0.0,both,NaN,0.0,left_only,NaN,left_only,0.0,left_only,0.0,NaN,left_only
jl_7ccd144baa4275ab,1.0,0.0,left_only,NaN,0.0,left_only,NaN,left_only,0.0,left_only,0.0,NaN,left_only
jl_ba19b2e0984e8e1f,1.0,3.0,both,NaN,0.0,left_only,1.0,both,1.0,both,1.0,Bioinformatics Scientist,both
jl_5f30454eae8a42bd,1.0,3.0,both,NaN,0.0,left_only,1.0,both,0.0,left_only,1.0,PhD Research Scientist- Machine Learning,both
jl_ba29f67e688108c5,1.0,2.0,both,NaN,0.0,left_only,1.0,both,0.0,left_only,0.0,NaN,left_only
jl_ffb7f83fa7858f6a,1.0,0.0,left_only,NaN,0.0,left_only,1.0,both,0.0,left_only,1.0,"Data Scientist, Algorithms",both
...,...,...,...,...,...,...,...,...,...,...,...,...,...
jl_7134025708fe7144,1.0,1.0,both,NaN,0.0,left_only,1.0,both,0.0,left_only,0.0,NaN,left_only
jl_a7e71b866947d01e,1.0,0.0,both,NaN,0.0,left_only,1.0,both,0.0,left_only,0.0,NaN,left_only
jl_fd766cb0b544acf9,1.0,0.0,left_only,NaN,0.0,left_only,1.0,both,0.0,left_only,1.0,Computational Scientist I,both
jl_aad34d95918a1375,1.0,3.0,both,NaN,0.0,left_only,NaN,left_only,0.0,left_only,1.0,Multimodal Machine Learning Scientist,both
jl_3eafa8edc774cce0,1.0,4.0,both,NaN,0.0,left_only,1.0,both,0.0,left_only,0.0,NaN,left_only
jl_1d247feb6e5e4473,1.0,0.0,left_only,NaN,0.0,left_only,0.0,both,0.0,left_only,1.0,Data Science Graduate Level Internship,both
jl_73cb2723d093d5ec,1.0,0.0,left_only,bioinformatics scientist / analyst,1.0,both,0.0,both,0.0,left_only,1.0,Bioinformatics Scientist / Analyst,both
jl_31572b6e494bcd16,1.0,4.0,both,NaN,0.0,left_only,1.0,both,0.0,left_only,1.0,Senior Data Scientist,both
jl_96ee8324d1984eb3,1.0,4.0,both,NaN,0.0,left_only,0.0,both,0.0,left_only,0.0,NaN,left_only
jl_74a2219a6d9549ea,1.0,0.0,left_only,computational biologist,0.0,both,0.0,both,0.0,left_only,0.0,NaN,left_only
jl_e962863ee226ea30,1.0,0.0,left_only,NaN,0.0,left_only,0.0,both,0.0,left_only,0.0,NaN,left_only
jl_1eb955eee5c52fde,1.0,2.0,both,NaN,0.0,left_only,NaN,left_only,0.0,left_only,0.0,NaN,left_only
jl_1c81b34b23854260,1.0,0.0,left_only,NaN,0.0,left_only,1.0,both,0.0,left_only,1.0,"Data Scientist / Quantitative Analyst, Enginee...",both
jl_a93cda6fbf6c0acb,1.0,0.0,both,NaN,0.0,left_only,NaN,left_only,0.0,left_only,0.0,NaN,left_only
jl_747d7a9796cc5430,1.0,0.0,left_only,NaN,0.0,left_only,1.0,both,0.0,left_only,1.0,Principal Data Scientist,both
jl_b9534037fb378bb2,1.0,3.0,both,NaN,0.0,left_only,NaN,left_only,0.0,left_only,1.0,Machine Learning Data Scientist,both
jl_e40649282f4e0b97,1.0,4.0,both,NaN,0.0,left_only,1.0,both,0.0,left_only,1.0,"Computational Biologist, Verily Life Sciences",both
jl_62f348807c98380f,1.0,0.0,both,NaN,0.0,left_only,1.0,both,0.0,left_only,0.0,NaN,left_only
jl_cb5fcfa7b0df11f9,1.0,3.0,both,NaN,0.0,left_only,1.0,both,0.0,left_only,0.0,NaN,left_only
jl_0aca95ef4434c6ee,1.0,0.0,left_only,NaN,0.0,left_only,1.0,both,0.0,left_only,0.0,NaN,left_only
jl_738e821e2461e436,1.0,0.0,left_only,NaN,0.0,left_only,NaN,left_only,0.0,left_only,1.0,Computer Vision / Machine Learning Algorithm D...,both
jl_04a294feed2acb5a,1.0,0.0,left_only,"data scientist, inflammation and immunology re...",1.0,both,1.0,both,0.0,left_only,1.0,"Data Scientist, Inflammation and Immunology Re...",both
jl_1056715d6afd92ce,1.0,2.0,both,NaN,0.0,left_only,0.0,both,0.0,left_only,0.0,NaN,left_only
jl_104372296a1d5292,1.0,0.0,both,NaN,0.0,left_only,1.0,both,0.0,left_only,1.0,Data Scientist,both
jl_6d0ea7974f64ab6b,1.0,2.0,both,NaN,0.0,left_only,1.0,both,0.0,left_only,0.0,NaN,left_only
jl_81cf0927167605ca,1.0,2.0,both,NaN,0.0,left_only,1.0,both,0.0,left_only,0.0,NaN,left_only
jl_7fd98a87cf190b3a,1.0,3.0,both,NaN,0.0,left_only,1.0,both,1.0,both,1.0,Imaging Data Curator,both
jl_f00342abd33b2727,1.0,0.0,left_only,NaN,0.0,left_only,NaN,left_only,0.0,left_only,0.0,NaN,left_only
jl_9778928e030197b4,1.0,3.0,both,NaN,0.0,left_only,1.0,both,0.0,left_only,1.0,"DATA SCIENTIST, WORLD-CLASS CONSULTANCY ROLE",both
jl_a7e5cadd2d2cf906,1.0,0.0,left_only,NaN,0.0,left_only,1.0,both,0.0,left_only,1.0,"PRINCIPAL DATA SCIENTIST, NON-PROFIT - LIFE-CH...",both

In [291]:
#df = df.dropna()
print(df.shape)
#df1 = df[pd.isnull(df.index)]
#print(df1)

#drop any rows with no index (job id)
df = df[pd.notnull(df.index)]
print(df.shape)

#drop any rows without a target (over 90K)
df = df[pd.notnull(df['over_90k'])]
print(df.shape)

(920, 13)
(919, 13)
(744, 13)

In [292]:
df.to_csv("my_csv.csv")

## Make Logistic Regression Model

In [295]:
from sklearn.linear_model import LogisticRegressionCV
X = df[[
        'years',
        'scientist_in_title',
        'has_startup',
        'has_phd'
    ]]
y = df.over_90k


model = LogisticRegressionCV(cv=3) 

model.fit(X, y) # This fits the model to learn the coefficients

LogisticRegressionCV(Cs=10, class_weight=None, cv=3, dual=False,
           fit_intercept=True, intercept_scaling=1.0, max_iter=100,
           multi_class='ovr', n_jobs=1, penalty='l2', random_state=None,
           refit=True, scoring=None, solver='lbfgs', tol=0.0001, verbose=0)

## Check scores etc.

In [321]:
model.scores_[1]

array([[ 0.53815261,  0.53815261,  0.53815261,  0.63052209,  0.61445783,
         0.59437751,  0.59437751,  0.59437751,  0.59437751,  0.59437751],
       [ 0.54032258,  0.54032258,  0.42741935,  0.45967742,  0.56854839,
         0.63306452,  0.63306452,  0.63306452,  0.63306452,  0.63306452],
       [ 0.53846154,  0.53846154,  0.53846154,  0.58704453,  0.58704453,
         0.58704453,  0.59919028,  0.59919028,  0.59919028,  0.59919028]])

In [274]:
from sklearn.cross_validation import cross_val_score

for metric in ['accuracy', 'precision', 'recall', 'roc_auc']:
    scores = cross_val_score(model, X, y, scoring=metric)
    print("mean {}: {}, all: {}".format(metric, scores.mean(), scores))

mean accuracy: 0.567129145199, all: [ 0.59437751  0.56854839  0.53846154]
mean precision: 0.626993238934, all: [ 0.64102564  0.70149254  0.53846154]
mean recall: 0.636815920398, all: [ 0.55970149  0.35074627  1.        ]
mean roc_auc: 0.605909315167, all: [ 0.62255029  0.53698612  0.65819153]

In [310]:
def examine_coefficients(model, df):
    df = pd.DataFrame(
        { 'Coefficient' : model.coef_[0] , 'Feature' : df.columns}
    ).sort_values(by='Coefficient')
    return df[df.Coefficient !=0 ]

examine_coefficients(model, X)

   Coefficient             Feature
1    -0.458136  scientist_in_title
0     0.154580               years
3     0.708252             has_phd
2     1.580908         has_startup

In [323]:
df_check = df[['has_startup','over_90k']]

## Conclusions

This model does not accurately predict whether a job will have a salary range of over 90K.

In this exercise the data used was incomplete and inaccurate at best.  The web scraping effort did not lend itself to a clean dataset.

That being said, the model is quite inaccurate and even with cleaner data it may not provide for better predictions.